version: "3.9"

services:

  api:
    build: .
    container_name: shl-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  web:
    build: .
    container_name: shl-web
    command: streamlit run web/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api